"""turn back

Revision ID: 1060670a165b
Revises: a6ba3bfa33f3
Create Date: 2019-05-16 22:06:51.693010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1060670a165b'
down_revision = 'a6ba3bfa33f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('army', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turns', sa.Integer(), server_default='60', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('army', schema=None) as batch_op:
        batch_op.drop_column('turns')

    # ### end Alembic commands ###
