"""avatars fix

Revision ID: 4fbfa204a572
Revises: 01bc2a7bcc4d
Create Date: 2019-06-26 18:29:42.189993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fbfa204a572'
down_revision = '01bc2a7bcc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(length=200),
               server_default='default.png',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=mysql.VARCHAR(length=200),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###
