"""turn deleted

Revision ID: a6ba3bfa33f3
Revises: 02cdd54b9810
Create Date: 2019-05-16 22:05:56.129068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ba3bfa33f3'
down_revision = '02cdd54b9810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('army', schema=None) as batch_op:
        batch_op.drop_column('turns')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('army', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turns', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
